### ISSUE TITLE
BadValue bad limit value in query

### ISSUE THREAD

**Issue by memolog** [frankdejonge/Monga#10]

**Comment by frankdejonge** [comment]
@memolog this package is not maintained anymore, it's located here now: https://github.com/thephpleague/monga

**Comment by frankdejonge** [comment]
@memolog also I'm pretty sure you've got the wrong repository, this is a PHP project.

**Comment by memolog** [comment]
I posted the wrong repository... I'm very sorry to bother you.

**Comment by frankdejonge** [comment]
@memolog no worries, good luck with your issue.
