### ISSUE TITLE
Update a collection in readme.md is that right?

### ISSUE THREAD

**Issue by stuchin** [frankdejonge/Monga#4]
in readme.md
// Update a collection
$collection->update(function($query){
    $query->increment('age')
        ->remove('nik')
        ->set('nick', 'FrenkyNet');
});

is that right? there is no binding to a specific document

**Comment by frankdejonge** [comment]
a document is a row, this would update all the documents in a collection, this is correct

**Comment by stuchin** [comment]
how then can update one document?
there are in Monga analog

public bool|array MongoCollection::update ( array $criteria , array $new_object [, array $options = array() ] )

**Comment by frankdejonge** [comment]
You can use `Monga\Collection::save`.

**Comment by patsToms** [comment]
Documentation examples is a little messy. Check example here - https://gist.github.com/patsToms/5382468 .
