### ISSUE TITLE
incomprehensible error

### ISSUE THREAD

**Issue by stuchin** [frankdejonge/Monga#6]
part of my code:

$email = "proba@proba.ru";
$user_count = $collection->find(function($query){ $query->where('email', $email);
 });

and I get the error
notice
Fuel\Core\PhpErrorException [ Notice ]: Undefined variable: email

where I was wrong?

**Comment by frankdejonge** [comment]
$user_count = $collection->find(function($query) use ($email) { $query->where('email', $email); } );
:dancers:
