### ISSUE TITLE
MongoCursorException: localhost:27017: Can't canonicalize query: BadValue bad sort specification

### ISSUE THREAD

**Issue by musaulker** [frankdejonge/Monga#9]
Hello,

I'm trying to pass query, skip and limit parameters as dynamically but I'm getting a **MongoCursorException**.

Exception details: 

**localhost:27017: Can't canonicalize query: BadValue bad sort specification**

``` php
$values = $collection->find(function($query){
        global $sortby, $sortdirection, $limit, $start;
        $query->orderBy($sortBy, $sortDirection)
            ->skip($start)
            ->limit($limit);
});
```

I've tried to debug the code and saw that all parameters that I'm trying to access with global identifier are passed as null. So is there a problem with accessing global parameters inside query section?

Thanks

**Comment by musaulker** [comment]
Upps! My fault.. I was trying to access a non-global variable inside my router. So I used use closure to pass parameters.

Thanks

**Comment by frankdejonge** [comment]
@musaulker I'd always recommend using the `use` statement when pulling stuff into a closure. Globals always get messy. Just as a tip :)

**Comment by musaulker** [comment]
Thanks @FrenkyNet ;)
